version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    image: rengarajk/news-feed-api
    container_name: backend
    depends_on: 
      - mongodb
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: rengarajk/news-feed-frontend
    container_name: frontend
    depends_on: 
      - backend
    ports:
      - "4173:4173"
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
